import { useState, useEffect, useCallback } from 'react';
import { Quote, RefreshCw } from 'lucide-react';
import { format } from 'date-fns';

interface QuoteData {
  quote: string;
  author: string;
}

// Add your preferred quotes here!
const PREFERRED_QUOTES: QuoteData[] = [
  { quote: "Preoccupied with a single leaf... you won't see the tree. Preoccupied with a single tree... you'll miss the entire forest. Don't be preoccupied with a single spot. See everything in its entirety... effortlessly. That is what it means to truly 'see.'", author: "Takuan Soho" },
  { quote: "Swimming in the middle of an ocean, one can never realize how vast it truly is.", author: "In'ei Hozoin" },
  { quote: "Don't let your mind rest anywhere. Don't let your mind rest on anyone. Keep flowing.", author: "Takuan Soho" },
  { quote: "All truly strong people are kind.", author: "Kamiizumi Ise-no-Kami" },
  { quote: "What is the meaning of 'strength'? It's to have a mind that does not sway, while continuing to move forward and change.", author: "Miyamoto Musashi" },
  { quote: "Invincible is merely a word.", author: "Miyamoto Musashi" },
  { quote: "There is no limit to technique. There is always room for improvement.", author: "Sekishusai Yagyu" },
  { quote: "There is no light for those who do not know darkness. Live on and endure the shadows, Takezo... and brightness shall come your way.", author: "Takuan Soho" },
  { quote: "Nothing goes perfectly for us. But being incomplete is what pushes us onward to the next something. If we were ever perfectly satisfied, what meaning would the rest of our lives hold, right?", author: "Takehiko Inoue" },
  { quote: "Each path born is by heaven perfectly decided and at once perfectly free.", author: "Takuan Soho" },
  { quote: "Life has no value! Truly right. It has no value. If you think only of yourself, it has no value. 'Why was I born?' The reason you are here is because someone supported your life... The reason you are here is to support lives.", author: "Miyamoto Musashi" },
  { quote: "I'm not gonna run away, I never go back on my word! That's my nindo: my ninja way.", author: "Naruto Uzumaki" },
  { quote: "A dropout will beat a genius through hard work.", author: "Rock Lee" },
  { quote: "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be.", author: "Naruto Uzumaki" },
  { quote: "A shinobi’s life is not measured by how they lived, but rather what they managed to accomplish before their death.", author: "Jiraiya" },
  { quote: "Sometimes you must hurt in order to know, fall in order to grow, lose in order to gain, because life's greatest lessons are learned through pain.", author: "Pain (Nagato)" },
  { quote: "People live their lives bound by what they accept as correct and true. That is how they define 'reality'. But what does it mean to be 'correct' or 'true'? Merely vague concepts... Their 'reality' may all be a mirage. Can we consider them to simply be living in their own world, shaped by their beliefs?", author: "Itachi Uchiha" },
  { quote: "Wake up to reality! Nothing ever goes as planned in this accursed world. The longer you live, the more you realize that the only things that truly exist in this reality are merely pain, suffering, and futility.", author: "Madara Uchiha" },
  { quote: "In the ninja world, those who break the rules are scum, that's true, but those who abandon their friends are worse than scum.", author: "Kakashi Hatake" },
  { quote: "It is only through the eyes of others that our lives have any meaning.", author: "Haku" },
  { quote: "When a man learns to love, he must bear the risk of hatred.", author: "Madara Uchiha" },
  { quote: "We are humans, not fish. We don't know what kind of people we truly are until the moment before our deaths. As death comes to embrace you, you will realize what you are. That's what death is, don't you think?", author: "Itachi Uchiha" },
  { quote: "Those who forgive themselves, and are able to accept their true nature... They are the strong ones!", author: "Itachi Uchiha" },
  { quote: "It is not wise to judge others based on your own preconceptions and by their appearances.", author: "Itachi Uchiha" },
  { quote: "Knowledge and awareness are vague, and perhaps better called illusions. Everyone lives within their own subjective interpretation.", author: "Itachi Uchiha" },
  { quote: "You focus on the trivial, and lose sight of what is most important. Change is impossible in this fog of ignorance.", author: "Itachi Uchiha" },
  { quote: "No single thing is perfect by itself. That’s why we’re born to attract other things to make up for what we lack. I think we start walking in the right direction only after we start getting our counterparts beside us.", author: "Itachi Uchiha" },
  { quote: "If you want to know who you are, you have to look at your real self and acknowledge what you see.", author: "Itachi Uchiha" },
  { quote: "He who forgives and acknowledges himself... that is what it truly means to be strong!", author: "Itachi Uchiha" },
  { quote: "Listen to me, Thorfinn. You have no enemies. No one... has any enemies. There is no one... that you should hurt.", author: "Thors Snorresson" },
  { quote: "A true warrior needs no sword.", author: "Thors Snorresson" },
  { quote: "You're a warrior now. So... become a true warrior, Thorfinn. Go beyond... the place where Thors went.", author: "Askeladd" },
  { quote: "A battle... where I don't kill anyone? That's the only kind of battle worth fighting.", author: "Thorfinn" },
  { quote: "I want what you have. I want to be a kinder person.", author: "Thorfinn" },
  { quote: "To build a country of peace... to build a place where people who don't need swords can live. Vinland.", author: "Thorfinn" },
  { quote: "The first step to building a peaceful land... is to never lift a sword, no matter what.", author: "Thorfinn" },
  { quote: "If I just sit here and die, then what the hell was my life all about? All the people I killed... what will their lives mean? I have to carry them. I have to live, and I have to create a world where their deaths weren't meaningless.", author: "Thorfinn" },
  { quote: "Love provides everything. It does not judge... This snow, it is love. It falls on everyone equally. But you humans... you discriminate. You love your family, you love your country, and so you fight for them. That is discrimination. True love... is to love all equally.", author: "Willibald" },
  { quote: "Look around you... It's a beautiful world, isn't it? But people... they just ruin it.", author: "Askeladd" },
  { quote: "To live... is to fight. To be alive is to struggle.", author: "Askeladd" },
  { quote: "Doctor Tenma. For you, all lives are created equal. That's why I came back to life. But you've finally come to realize it now, haven't you? Only one thing is equal for all, and that is death.", author: "Johan Liebert" },
  { quote: "There's nothing special about being born. Not a thing. Most of the universe is just death, nothing more. In this universe of ours, the birth of a new life on some corner of our planet is nothing but a tiny, insignificant flash. Death is a normal thing. So why live?", author: "Johan Liebert" },
  { quote: "Hatred is born when people gather together.", author: "Johan Liebert" },
  { quote: "How weak the mind is when it wants to forget. Maybe you didn't forget. Maybe you're just lying to yourself. Is it a lie you tell to everyone around you, or perhaps a lie you tell to yourself?", author: "Johan Liebert" },
  { quote: "Do you think your sin will disappear if you lie?", author: "Johan Liebert" },
  { quote: "The big secret to breaking the rules is to make it look as though you're following them.", author: "Johan Liebert" },
  { quote: "Tell me, what do you think is the ultimate fear? I really thought that I had already reached the darkest of the dark, but then, ahead of me, I beheld an even greater darkness.", author: "Johan Liebert" },
  { quote: "The end? What is the end? I've seen the end many times. What is the end?", author: "Johan Liebert" },
  { quote: "Look at me! Look at me! The monster inside of me has gotten this big!", author: "Johan Liebert" },
  { quote: "While many can pursue their dreams in solitude, other dreams are like great storms blowing hundreds, even thousands of dreams apart in their wake. Dreams breathe life into men and can cage them in suffering. Men live and die by their dreams. But long after they have been abandoned they still smolder deep in men's hearts. Some see nothing but life and death. They are dead, for they have no dreams.", author: "Griffith" },
  { quote: "A man who would do nothing but live out his life just because he happened to be born... is someone I cannot accept.", author: "Griffith" },
  { quote: "I will not betray my dream. That is all.", author: "Griffith" },
  { quote: "It is my perception, that a true friend never relies on another's dream. A person with the potential to be my true friend, must be able to find his reason for life without my help. And, he would have to put his heart and soul into protecting his dream. He would never hesitate to fight for his dream, even against me. For me, a true friend is one who stands equal to me in all respects.", author: "Griffith" },
  { quote: "Among thousands of comrades and ten thousand enemies, only you... only you made me forget my dream.", author: "Griffith" },
  { quote: "If you're going to fight, then you shouldn't care what happens to you. If you don't want to die... then you shouldn't fight. Those who fight on the battlefield know that they could die at any moment.", author: "Griffith" },
  { quote: "To realize my dream, I will perch on top of their corpses. It is a blood-smeared dream, after all. I don't regret or feel guilty about it. But to risk thousands of lives while never getting my own hands dirty... It's not a dream that can be so easily realized!", author: "Griffith" },
  { quote: "There is no such thing as 'truth' or 'lies' in this world; there never has been. There are only plain, hard facts. And yet, all beings who exist in this world acknowledge only those 'facts' that are convenient to them, and take them to be the 'truth.' They do so because they know no other way of living. However, for those powerless beings who comprise the majority of this world's population, inconvenient facts that affirm their very existence, are their only truth.", author: "Sosuke Aizen" },
  { quote: "Since when were you under the illusion that I wasn't using Kyoka Suigetsu?", author: "Sosuke Aizen" },
  { quote: "Admiration is the furthest state from understanding.", author: "Sosuke Aizen" },
  { quote: "No one stands on the top of the world. Not you, not me, not even gods. But the unbearable vacancy of the throne in the sky is over. From now on... I will be sitting on it.", author: "Sosuke Aizen" },
  { quote: "A victor must speak not of the current state of the world, but of how it should rightfully be.", author: "Sosuke Aizen" },
  { quote: "Why are you putting so much distance between us? If you want to make sure it hits me, then you should get close and fire. Or is it that you're afraid of letting even a part of me out of your field of vision by getting close? If that's the case, then it's a foolish thought. Distance only has meaning in a fight between equals. With you and I, distance holds no meaning at all.", author: "Sosuke Aizen" },
  { quote: "Trusting someone... means relying on them. And that's something the weak do. We have no need for it.", author: "Sosuke Aizen" },
  { quote: "All creatures want to believe in something bigger than themselves. They cannot live without blind obedience. And to escape the pressure of that trust, those in whom faith is placed in turn look for someone higher than themselves. And then those people in turn look for someone even stronger. That is how all Kings are born. That is how all Gods are born.", author: "Sosuke Aizen" },
  { quote: "Fear is necessary for evolution. The fear that one could be destroyed at any moment.", author: "Sosuke Aizen" },
  { quote: "I'm not gonna run away, I never go back on my word! That's my nindo: my ninja way.", author: "Naruto Uzumaki" },
  { quote: "Push through the pain. Giving up hurts more.", author: "Vegeta" },
  { quote: "A dropout will beat a genius through hard work.", author: "Rock Lee" },
  { quote: "I do not fear this new challenge. Rather, like a true warrior I will rise to meet it.", author: "Vegeta" },
  { quote: "If you lose, you die. If you win, you live. If you don't fight, you can't win!", author: "Eren Yeager" },
  { quote: "When you give up, that's when the game ends.", author: "Mitsuyoshi Anzai" },
  { quote: "If you don't take risks, you can't create a future!", author: "Monkey D. Luffy" },
  { quote: "Hard work is worthless for those that don't believe in themselves.", author: "Naruto Uzumaki" },
  { quote: "A true warrior needs no sword.", author: "Thors Snorresson" },
  { quote: "There's no shame in falling down! True shame is to not stand up again!", author: "Shintaro Midorima" },
  { quote: "Miracles happen to those who never give up.", author: "Emporio Ivankov" },
  { quote: "If you don't like your destiny, don't accept it. Instead, have the courage to change it.", author: "Naruto Uzumaki" },
  { quote: "Giving up kills people. When people reject giving up... they finally win the right to transcend humanity.", author: "Alucard" },
  { quote: "Stand up and walk. Keep moving forward. You've got two good legs. So get up and use them.", author: "Edward Elric" },
  { quote: "To realize my dream, I will perch on top of their corpses.", author: "Griffith" },
  { quote: "People live their lives bound by what they accept as correct and true. That is how they define 'reality'.", author: "Itachi Uchiha" },
  { quote: "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful.", author: "Roy Mustang" },
  { quote: "There is no such thing as 'truth' or 'lies' in this world; there never has been. There are only plain, hard facts.", author: "Sosuke Aizen" },
  { quote: "Fear is freedom! Subjugation is liberation! Contradiction is truth! Those are the facts of this world!", author: "Satsuki Kiryuin" },
  { quote: "If you use your head, you won't get fat even if you eat sweets.", author: "L Lawliet" },
  { quote: "Simplicity is the easiest path to true beauty.", author: "Seishuu Handa" },
  { quote: "You should enjoy the little detours to the fullest. Because that's where you'll find the things more important than what you want.", author: "Ging Freecss" },
  { quote: "A battle... where I don't kill anyone? That's the only kind of battle worth fighting.", author: "Thorfinn" },
  { quote: "Wake up to reality! Nothing ever goes as planned in this accursed world.", author: "Madara Uchiha" },
  { quote: "Fools who don't respect the past are likely to repeat it.", author: "Nico Robin" },
  { quote: "The past is the past. We cannot indulge ourselves in memories and destroy the present.", author: "Ken Murata" },
  { quote: "The difference between a novice and a master is that a master has failed more times than a novice has tried.", author: "Koro-sensei" },
  { quote: "Growth occurs when one goes beyond one's limits.", author: "Itachi Uchiha" },
  { quote: "Fear is not evil. It tells you what your weakness is. And once you know your weakness, you can become stronger as well as kinder.", author: "Gildarts Clive" },
  { quote: "Human strength lies in the ability to change yourself.", author: "Saitama" },
  { quote: "A dream... It's something you do for yourself, not for others.", author: "Guts" },
  { quote: "If you wanna make people dream, you've gotta start by believing in that dream yourself!", author: "Seiya Kanie" },
  { quote: "Men live and die by their dreams.", author: "Griffith" },
  { quote: "We are not defined by our past, but by the choices we make in the present.", author: "Kirito" },
  { quote: "Whatever you lose, you'll find it again. But what you throw away you'll never get back.", author: "Kenshin Himura" },
  { quote: "It's quiet, but can you hear it? Little by little, the tides are changing, and the world with them.", author: "Shakuyaku" },
  { quote: "If you can't find a reason to fight, then you shouldn't be fighting.", author: "Akame" },
  { quote: "A life that lives without doing anything is the same as a slow death.", author: "Lelouch vi Britannia" },
  { quote: "There are ends we don't desire, but they're inevitable; we have to face them. It's what being human is all about.", author: "Jet Black" },
  { quote: "I hate perfection. To be perfect is to be unable to improve any further.", author: "Mayuri Kurotsuchi" },
  { quote: "If you only face forward, there is something you will miss seeing.", author: "Jiji" },
  { quote: "All we can do is live until the day we die. Control what we can... and fly free.", author: "Deneil Young" },
  { quote: "The circumstances of one's birth are irrelevant. It is what you do with the gift of life that determines who you are.", author: "Mewtwo" },
  { quote: "The universe has a beginning, but no end. — Infinity. Stars, too, have their own beginnings, but their own power results in their destruction. — Finite.", author: "Rintarou Okabe" },
  { quote: "The only thing we're allowed to do is believe that we won't regret the choice we made.", author: "Levi Ackerman" },
  { quote: "Sometimes you must hurt in order to know, fall in order to grow, lose in order to gain.", author: "Pain" },
  { quote: "If you don't share someone's pain, you can never understand them.", author: "Nagato" },
  { quote: "To know sorrow is not terrifying. What is terrifying is to know you can't go back to the happiness you could have.", author: "Rangiku Matsumoto" },
  { quote: "Forgetting is like a wound. The wound may heal, but it has already left a scar.", author: "Monkey D. Luffy" },
  { quote: "The thread of human hope is spun with the flax of sorrow.", author: "Kaworu Nagisa" },
  { quote: "Knowing what it feels like to be in pain is exactly why we try to be kind to others.", author: "Jiraiya" },
  { quote: "The scars you can't see are the hardest to heal.", author: "Nao Tomori" },
  { quote: "I'm just watching a bad dream I never wake up from.", author: "Spike Spiegel" },
  { quote: "You can die anytime, but living takes true courage.", author: "Kenshin Himura" },
  { quote: "The loneliest people are the kindest. The saddest people smile the brightest.", author: "Jellal Fernandes" },
  { quote: "Forgetting the pain of those you killed is no different than killing them a second time.", author: "Kenshin Himura" },
  { quote: "Revenge is just the path you take to escape your suffering.", author: "Ichigo Kurosaki" },
  { quote: "Are you crying because you're sad, or are you crying because you're happy?", author: "Vash the Stampede" },
  { quote: "Loneliness is peaceful, but very lonely.", author: "Yukino Yukinoshita" },
  { quote: "I just want to live a life without being hated.", author: "Shoya Ishida" },
  { quote: "In the ninja world, those who break the rules are scum. But those who abandon their friends are worse than scum.", author: "Kakashi Hatake" },
  { quote: "I want you to be happy. I want you to laugh a lot. I don't know what exactly I'll be able to do for you, but I'll always be by your side.", author: "Kagome Higurashi" },
  { quote: "A true friend never relies on another's dream. A person with the potential to be my true friend must be able to find his reason for life without my help.", author: "Griffith" },
  { quote: "It is only through the eyes of others that our lives have any meaning.", author: "Haku" },
  { quote: "No single thing is perfect by itself. That's why we're born to attract other things to make up for what we lack.", author: "Itachi Uchiha" },
  { quote: "Everyone has things they can do and cannot do. I'll do what you can't do, and you do what I can't do.", author: "Sanji" },
  { quote: "There comes a time when a man must stand and fight. And that is when his friends' dreams are being laughed at!", author: "Usopp" },
  { quote: "We are all like fireworks: We climb, we shine and always go our separate ways. But let's not disappear like a firework and continue to shine forever.", author: "Toshiro Hitsugaya" },
  { quote: "I won't let anyone die! Not another single person!", author: "Tanjiro Kamado" },
  { quote: "When a man learns to love, he must bear the risk of hatred.", author: "Madara Uchiha" },
  { quote: "Remember that everyone you meet is afraid of something, loves something, and has lost something.", author: "Lucy Heartfilia" },
  { quote: "If you wanna save people, save yourself first!", author: "Kyojuro Rengoku" },
  { quote: "A heart's a heavy burden.", author: "Sophie Hatter" },
  { quote: "No matter how many weapons you have... the world cannot live without love.", author: "Sheeta" },
  { quote: "I don't care if no one likes me, I wasn't created in this world to entertain everyone.", author: "Houtarou Oreki" },
  { quote: "People's lives don't end when they die. It ends when they lose faith.", author: "Itachi Uchiha" },
  { quote: "Only one thing is equal for all, and that is death.", author: "Johan Liebert" },
  { quote: "Why should I apologize for being a monster? Has anyone ever apologized for turning me into one?", author: "Juuzou Suzuya" },
  { quote: "It's not dying that frightens us. It's living without ever having done our best.", author: "The Elder" },
  { quote: "Those who forgive themselves, and are able to accept their true nature... They are the strong ones!", author: "Itachi Uchiha" },
  { quote: "The strong should aid and protect the weak. Then, the weak will become strong.", author: "Tanjiro Kamado" },
  { quote: "Those who stand at the top determine what's wrong and what's right! Whoever wins this war becomes justice!", author: "Donquixote Doflamingo" },
  { quote: "Hatred is born when people gather together.", author: "Johan Liebert" },
  { quote: "Look at me. Look at the monster inside me. Then tell me you can still love me.", author: "Johan Liebert" },
  { quote: "Religion, ideology, resources, land, spite, love or just because... no matter how pathetic the reason, it's enough to start war.", author: "Pain" },
  { quote: "To know you're powerless is to know you're human.", author: "Greed" },
  { quote: "People, who can't throw something important away, can never hope to change anything.", author: "Armin Arlert" },
  { quote: "In our society, those without power are left behind.", author: "Eren Yeager" },
  { quote: "If one can be proud of one's life, one should not wish for another chance.", author: "Saber" },
  { quote: "The important thing is not how long you live. It's what you accomplish with your life.", author: "Grovyle" },
  { quote: "I am the hope of the universe. I am the answer to all living things that cry out for peace... I am the Super Saiyan, Son Goku!", author: "Goku" },
  { quote: "Set your heart ablaze.", author: "Kyojuro Rengoku" },
  { quote: "Since when were you under the illusion that I wasn't using Kyoka Suigetsu?", author: "Sosuke Aizen" },
  { quote: "No one stands on the top of the world. Not you, not me, not even gods... From now on, I alone will stand at the top.", author: "Sosuke Aizen" },
  { quote: "Power comes in response to a need, not a desire. You have to create that need.", author: "Goku" },
  { quote: "Now for a lesson. You may have heard these words before, but I'll teach you what they really mean. Go beyond! PLUS ULTRA!", author: "All Might" },
  { quote: "I will be the Pirate King!", author: "Monkey D. Luffy" },
  { quote: "Listen to me, Thorfinn. You have no enemies. No one has any enemies.", author: "Thors Snorresson" },
  { quote: "My whole life, I have never fought thinking there was even a chance I could lose!", author: "All Might" },
  { quote: "In this world, wherever there is light, there are also shadows. As long as the concept of winners exists, there must also be losers.", author: "Madara Uchiha" },
  { quote: "The only ones who should kill are those who are prepared to be killed.", author: "Lelouch vi Britannia" },
  { quote: "To defeat evil, I must become a greater evil.", author: "Lelouch vi Britannia" },
  { quote: "A lesson without pain is meaningless. That's because no one can gain without sacrificing something. But by enduring that pain and overcoming it, he shall obtain a powerful, unmatched heart. A fullmetal heart.", author: "Edward Elric" },
  { quote: "In the hands of an incompetent, power brings nothing but ruin.", author: "Meruem" },
  { quote: "You believe I cannot pray with a single arm? A prayer comes from the heart.", author: "Isaac Netero" },
  { quote: "Peace under an illusion is nothing but a hollow lie.", author: "Gaara" },
  { quote: "I do not fear death. I fear only that my rage will fade over time.", author: "Kurapika" },
  { quote: "There is no such thing as peace in this world—that is reality. And reality is like this grand river, no matter how hard you try to swim against it, you will eventually be swallowed by it.", author: "Madara Uchiha" },
  { quote: "If you let the fly live, the spider is going to die. You can't save both without one suffering.", author: "Knives Millions" },
  { quote: "Men are not men on the battlefield. They turn into beasts. It's the only way they can survive.", author: "Guts" },
  { quote: "This world is rotten, and those who are making it rot deserve to die.", author: "Light Yagami" },
  { quote: "Fake people have an image to maintain. Real people just don't care.", author: "Hachiman Hikigaya" },
  { quote: "The world is not beautiful, therefore it is.", author: "Kino" },
  { quote: "There is no such thing as luck in this world. Rules, prerequisites, psychological states... there are any number of invisible factors that combine to produce an unpredictable, but inevitable result.", author: "Sora" },
  { quote: "It's exactly because we have no power that we can achieve anything.", author: "Shiro" },
  { quote: "I think you can't truly understand someone until you've fought them.", author: "Son Goku" },
  { quote: "Law doesn't protect people. People protect the law.", author: "Akane Tsunemori" },
  { quote: "Do you think a person can change? Or is it that their true nature is simply revealed?", author: "Shinya Kogami" },
  { quote: "The only thing that can defeat power is more power.", author: "Albert Wesker" },
  { quote: "Humans are driven by their own desires, but it is precisely because they have desires that they can evolve.", author: "Kyubey" },
  { quote: "Listen Simon... Don't forget. Believe in yourself. Not in the you who believes in me. Not the me who believes in you. Believe in the you who believes in yourself.", author: "Kamina" },
  { quote: "You're gonna carry that weight.", author: "Title Card, Cowboy Bebop" },
  { quote: "I don't want to conquer anything. It's just that the person with the most freedom on the sea is the Pirate King.", author: "Monkey D. Luffy" },
  { quote: "A half-moon. A bright half and a dark half. Just like me.", author: "Yuno Gasai" },
  { quote: "Whatever you do, enjoy it to the fullest. That is the secret of life.", author: "Rider (Iskandar)" },
  { quote: "Even if I die, you keep living, okay? Live to see the end of this world, and to see why it was born.", author: "Misato Katsuragi" },
  { quote: "The ticket to the future is always blank.", author: "Vash the Stampede" },
  { quote: "You can't sit around envying other people's worlds. You have to go out and change your own.", author: "Shinichi Chiaki" },
  { quote: "Whether a fish lives in a clear stream or a water ditch, so long as it continues swimming forward, it will grow up beautifully.", author: "Koro-sensei" },
  { quote: "We are all like fireworks: we climb, we shine and always go our separate ways and become further apart. But even when that time comes, let's not disappear like a firework and continue to shine forever.", author: "Toshiro Hitsugaya" },
  { quote: "When do you think people die? When they are shot through the heart by the bullet of a pistol? No. When they are ravaged by an incurable disease? No. When they drink a soup made from a poisonous mushroom? No! It’s when... they are forgotten.", author: "Dr. Hiriluk" },
  { quote: "Even if we forget the faces of our friends, we will never forget the bonds that were carved into our souls.", author: "Yuzuru Otonashi" },
  { quote: "If I can meet you again, against the 6 billion to 1 odds, even if you can't move, I'll marry you.", author: "Hideki Hinata" },
  { quote: "It's just as you said, I'm a monster. So what?", author: "Guts" },
  { quote: "I was dead until I met you. I was a powerless corpse pretending to be alive.", author: "Lelouch vi Britannia" },
  { quote: "Even if I lose this feeling, I'm sure I'll just fall in love with you all over again.", author: "Syaoran Li" },
  { quote: "To know sorrow is not terrifying. What is terrifying is to know you can't go back to the happiness you could have.", author: "Matsumoto Rangiku" },
  { quote: "Time waits for no one.", author: "Chiyaki Mamiya" },
  { quote: "A secret makes a woman, woman.", author: "Vermouth" },
  { quote: "Those who cannot acknowledge themselves will eventually fail.", author: "Itachi Uchiha" },
  { quote: "Omae wa mou shindeiru. (You are already dead.)", author: "Kenshiro" },
  { quote: "Bang.", author: "Spike Spiegel" },
  { quote: "Just who the hell do you think we are?!", author: "Simon & Kamina" },
  { quote: "I, Giorno Giovanna, have a dream.", author: "Giorno Giovanna" },
  { quote: "People die if they are killed.", author: "Shirou Emiya" },
  { quote: "I'll take a potato chip... and eat it!", author: "Light Yagami" },
  { quote: "El Psy Kongroo.", author: "Rintarou Okabe" },
  { quote: "Are you ready for this? I know I am.", author: "Bruno Bucciarati" },
  { quote: "Good grief. (Yare yare daze.)", author: "Jotaro Kujo" },
  { quote: "I am justice!", author: "Light Yagami / L" },
  { quote: "The thing called justice changes its shape depending on where you stand.", author: "Kuzan (Aokiji)" },
  { quote: "There is no Heaven or Hell. No matter what you do while you're alive, everybody goes to Mu (nothingness). Death is equal.", author: "Ryuk" },
  { quote: "If the king doesn't move, then his subjects won't follow.", author: "Lelouch vi Britannia" },
  { quote: "Justice is a weapon. It can be used to cause harm, but it cannot protect or save others.", author: "Osamu Dazai" },
  { quote: "What is right? What is wrong? In this mixed up world, deciding what is right and wrong is not easy. You can't just go by somebody else's rules. If you let yourself be controlled like that, you'll just become a puppet that can't make decisions on its own. You have to live by your rules.", author: "Gintoki Sakata" },
  { quote: "Do you know where hell is? Inside your head.", author: "Crona" },
  { quote: "Is there a reason you have to kill people? I don't know why you would kill someone, but to save someone... a logical reason isn't necessary.", author: "Shinichi Kudo" },
  { quote: "Those who do not understand true pain can never understand true peace.", author: "Pain" },
  { quote: "There are no such things as miracles in this world. Only inevitabilities and accidents.", author: "Yuuko Ichihara" },
  { quote: "To act is not necessarily compassion. True compassion sometimes comes from inaction.", author: "Hinata Miyake" },
  { quote: "Surpass your limits. Right here, right now.", author: "Yami Sukehiro" },
  { quote: "Who decides that? I am the only one who decides.", author: "Escanor" },
  { quote: "My soldiers, rage! My soldiers, scream! My soldiers, fight!", author: "Erwin Smith" },
  { quote: "If you feel yourself hitting up against your limit, remember for what cause you clench your fists!", author: "All Might" },
  { quote: "Let me show you how a real man fights!", author: "Kamina" },
  { quote: "If you’re gonna be a wall, I’m gonna smash you to pieces!", author: "Izuku Midoriya" },
  { quote: "You need to accept the fact that you’re not the best and have all the will to strive to be better than anyone you face.", author: "Roronoa Zoro" },
  { quote: "A scar on the back is a swordsman's shame.", author: "Roronoa Zoro" },
  { quote: "I’m going to destroy this messed-up world!", author: "Ken Kaneki" },
  { quote: "Don't beg for things, do it yourself, or else you won't get anything.", author: "Renton Thurston" },
  { quote: "The world is merciless, and it's also very beautiful.", author: "Mikasa Ackerman" },
  { quote: "The night is in its darkest just before dawn. But keep your eyes open. If you avert your eyes from the dark, you'll be blind to the rays of a new day.", author: "Gintoki Sakata" },
  { quote: "When do people give up? When they realize it's impossible? No. They give up when they lose their will to fight.", author: "Armin Arlert" },
  { quote: "I don't want to live a thousand years. If I just live through today, that'll be enough.", author: "Portgas D. Ace" },
  { quote: "If you just submit yourself to fate, then that's the end of it.", author: "Keiichi Maebara" },
  { quote: "I don’t want to be someone who just protects things. I want to be someone who can change things.", author: "Shirou Emiya" },
  { quote: "Humans die. Animals die. Plants die. Even soul reapers die. It's the arch of the universe.", author: "Baraggan Louisenbairn" },
  { quote: "I am a ghoul.", author: "Ken Kaneki" },
  { quote: "You're only a kid once, so do what you want to do.", author: "Yoko Littner" },
  { quote: "If you don't like your situation, then change it.", author: "Chuuya Nakahara" },
  { quote: "A person grows up when he's able to overcome hardships. Protection is important, but there are some things that a person must learn on his own.", author: "Jiraiya" },
  { quote: "Talent is something you make bloom, instinct is something you polish.", author: "Tooru Oikawa" },
  { quote: "Being weak is nothing to be ashamed of. Staying weak is.", author: "Fuegoleon Vermillion" },
  { quote: "People become stronger because they have memories they can't forget.", author: "Tsunade" },
  { quote: "Mistakes are not shackles that halt one from stepping forward. Rather, they are that which sustain and grow one’s heart.", author: "Mavis Vermillion" },
  { quote: "A teacher doesn't give up on their students.", author: "Koro-sensei" },
  { quote: "I want to be a kind person because kind people are strong.", author: "Ken Kaneki" },
  { quote: "If it's possible for one person to be hurt by another, then it's possible for that person to be healed by another.", author: "Sohma Hatori" },
  { quote: "We might be scared, but that’s what makes us humans.", author: "Death the Kid" },
  { quote: "The moment you find the courage to give up your life for someone... would be the moment you understand love.", author: "Kenshin Himura" },
  { quote: "I love you. I loved you from the moment I first saw you.", author: "Rem" },
  { quote: "The reason I'm here is because you're here.", author: "Asuna" },
  { quote: "You're not alone. We are partners. If you are a witch, then I'll become a warlock.", author: "Lelouch vi Britannia" },
  { quote: "I will not let my comrades die. I will protect you with my life.", author: "Erza Scarlet" },
  { quote: "Sometimes, the things that matter the most are right in front of you.", author: "Asuna" },
  { quote: "Even if I'm not with you, I will always, always love you.", author: "Homura Akemi" },
  { quote: "A true king never lets his subjects see his tears.", author: "Sinbad" },
  { quote: "In this world, there are very few people who actually trust each other.", author: "Light Yagami" },
  { quote: "I have no interest in ordinary humans.", author: "Haruhi Suzumiya" },
  { quote: "If you are hungry, eat.", author: "Monkey D. Luffy" },
  { quote: "Frankly, my dear, I don't give a damn.", author: "Rhett Butler" },
  { quote: "I'm gonna make him an offer he can't refuse.", author: "Vito Corleone" },
  { quote: "Here's looking at you, kid.", author: "Rick Blaine" },
  { quote: "Toto, I've a feeling we're not in Kansas anymore.", author: "Dorothy Gale" },
  { quote: "You talkin' to me?", author: "Travis Bickle" },
  { quote: "You can't handle the truth!", author: "Col. Nathan R. Jessup" },
  { quote: "I love the smell of napalm in the morning.", author: "Lt. Col. Bill Kilgore" },
  { quote: "Fasten your seatbelts. It's going to be a bumpy night.", author: "Margo Channing" },
  { quote: "Say 'hello' to my little friend!", author: "Tony Montana" },
  { quote: "Are you not entertained?!", author: "Maximus Decimus Meridius" },
  { quote: "No. I am your father.", author: "Darth Vader" },
  { quote: "May the Force be with you.", author: "General Dodonna / Han Solo" },
  { quote: "I'll be back.", author: "The Terminator" },
  { quote: "All those moments will be lost in time, like tears in rain.", author: "Roy Batty" },
  { quote: "The first rule of Fight Club is: You do not talk about Fight Club.", author: "Tyler Durden" },
  { quote: "There is no spoon.", author: "Spoon Boy" },
  { quote: "I see dead people.", author: "Cole Sear" },
  { quote: "My precious.", author: "Gollum" },
  { quote: "Houston, we have a problem.", author: "Jim Lovell" },
  { quote: "Roads? Where we're going we don't need roads.", author: "Dr. Emmett Brown" },
  { quote: "I am not in danger, Skyler. I am the danger. A guy opens his door and gets shot and you think that of me? No. I am the one who knocks!", author: "Walter White" },
  { quote: "When you play the game of thrones, you win or you die. There is no middle ground.", author: "Cersei Lannister" },
  { quote: "Winter is coming.", author: "Ned Stark" },
  { quote: "If you don't like what's being said, change the conversation.", author: "Don Draper" },
  { quote: "The truth is out there.", author: "Fox Mulder" },
  { quote: "Omar comin'!", author: "Omar Little" },
  { quote: "Clear eyes, full hearts, can't lose.", author: "Coach Eric Taylor" },
  { quote: "Some people choose to see the ugliness in this world, the disarray. I choose to see the beauty.", author: "Dolores Abernathy" },
  { quote: "A man's got to have a code.", author: "Omar Little" },
  { quote: "In this terrifying world, all we have are the connections that we make.", author: "BoJack Horseman" },
  { quote: "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.", author: "Ferris Bueller" },
  { quote: "It's not a lie if you believe it.", author: "George Costanza" },
  { quote: "How you doin'?", author: "Joey Tribbiani" },
  { quote: "That's what she said.", author: "Michael Scott" },
  { quote: "I'm not superstitious, but I am a little stitious.", author: "Michael Scott" },
  { quote: "There's always money in the banana stand.", author: "George Bluth Sr." },
  { quote: "To infinity and beyond!", author: "Buzz Lightyear" },
  { quote: "Just keep swimming.", author: "Dory" },
  { quote: "I feel the need—the need for speed!", author: "Maverick and Goose" },
  { quote: "Good morning, and in case I don't see ya, good afternoon, good evening, and good night!", author: "Truman Burbank" },
  { quote: "Get busy living, or get busy dying.", author: "Andy Dufresne" },
  { quote: "Carpe diem. Seize the day, boys. Make your lives extraordinary.", author: "John Keating" },
  { quote: "Why do we fall, sir? So that we can learn to pick ourselves up.", author: "Alfred Pennyworth" },
  { quote: "Life is like a box of chocolates. You never know what you're gonna get.", author: "Forrest Gump" },
  { quote: "It is not our abilities that show what we truly are… it is our choices.", author: "Albus Dumbledore" },
  { quote: "Do, or do not. There is no try.", author: "Yoda" },
  { quote: "You is kind. You is smart. You is important.", author: "Aibileen Clark" },
  { quote: "Some birds aren't meant to be caged. Their feathers are just too bright.", author: "Red" },
  { quote: "Nobody puts Baby in a corner.", author: "Johnny Castle" },
  { quote: "Every man dies, not every man really lives.", author: "William Wallace" },
  { quote: "You come at the king, you best not miss.", author: "Omar Little" },
  { quote: "Chaos isn't a pit. Chaos is a ladder.", author: "Petyr 'Littlefinger' Baelish" },
  { quote: "I love you, but you are not serious people.", author: "Logan Roy" },
  { quote: "Those who want respect, give respect.", author: "Tony Soprano" },
  { quote: "Time is a flat circle.", author: "Rust Cohle" },
  { quote: "Just because you shot Jesse James, don't make you Jesse James.", author: "Mike Ehrmantraut" },
  { quote: "By order of the Peaky Blinders.", author: "Arthur Shelby" },
  { quote: "If you think this has a happy ending, you haven't been paying attention.", author: "Ramsay Bolton" },
  { quote: "Every lie we tell incurs a debt to the truth. Sooner or later, that debt is paid.", author: "Valery Legasov" },
  { quote: "Tread lightly.", author: "Walter White" },
  { quote: "This is the way.", author: "The Armorer / Din Djarin" },
  { quote: "We have to go back!", author: "Jack Shephard" },
  { quote: "People assume that time is a strict progression of cause to effect, but actually from a non-linear, non-subjective viewpoint, it's more like a big ball of wibbly-wobbly, timey-wimey... stuff.", author: "The Tenth Doctor" },
  { quote: "Friends don't lie.", author: "Eleven" },
  { quote: "I want to believe.", author: "Fox Mulder" },
  { quote: "So say we all!", author: "Commander William Adama" },
  { quote: "Don't blink. Blink and you're dead.", author: "The Tenth Doctor" },
  { quote: "Saving people, hunting things, the family business.", author: "Dean Winchester" },
  { quote: "The night is dark and full of terrors.", author: "Melisandre" },
  { quote: "We are the walking dead.", author: "Rick Grimes" },
  { quote: "PIVOT!", author: "Ross Geller" },
  { quote: "Identity theft is not a joke, Jim! Millions of families suffer every year.", author: "Dwight Schrute" },
  { quote: "Treat yo' self.", author: "Tom Haverford & Donna Meagle" },
  { quote: "I've made a huge mistake.", author: "Gob Bluth" },
  { quote: "Bazinga!", author: "Sheldon Cooper" },
  { quote: "Title of your sex tape.", author: "Jake Peralta" },
  { quote: "Legen—wait for it—dary!", author: "Barney Stinson" },
  { quote: "Ew, David!", author: "Alexis Rose" },
  { quote: "Nothing good happens after 2 a.m.", author: "Ted Mosby" },
  { quote: "Yada, yada, yada.", author: "Elaine Benes / Various" },
  { quote: "What is grief, if not love persevering?", author: "Vision" },
  { quote: "It gets easier. Every day it gets a little easier. But you gotta do it every day. That's the hard part.", author: "The Jogging Baboon" },
  { quote: "Pride is not the opposite of shame, but its source. True humility is the only antidote to shame.", author: "Uncle Iroh" },
  { quote: "I wish there was a way to know you're in the good old days before you've actually left them.", author: "Andy Bernard" },
  { quote: "Nobody exists on purpose. Nobody belongs anywhere. Everybody's gonna die. Come watch TV.", author: "Morty Smith" },
  { quote: "Every time someone steps up and says who they are, the world becomes a better, more interesting place.", author: "Captain Raymond Holt" },
  { quote: "The universe is a cruel, uncaring void. The key to being happy isn't a search for meaning. It's to just keep yourself busy with unimportant nonsense, and eventually, you'll be dead.", author: "Mr. Peanutbutter" },
  { quote: "Sometimes life is like this dark tunnel. You can't always see the light at the end of the tunnel, but if you just keep moving... you will come to a better place.", author: "Uncle Iroh" },
  { quote: "Hair is everything. We wish it wasn't so we could actually think about something else occasionally. But it is.", author: "Fleabag" },
  { quote: "We’re all stories, in the end. Just make it a good one, eh?", author: "The Eleventh Doctor" },
  { quote: "I'm not a psychopath, I'm a high-functioning sociopath. Do your research.", author: "Sherlock Holmes" },
  { quote: "You know nothing, Jon Snow.", author: "Ygritte" },
  { quote: "I am the one who knocks!", author: "Walter White" },
  { quote: "I will take what is mine with fire and blood.", author: "Daenerys Targaryen" },
  { quote: "You don't need a criminal lawyer. You need a criminal lawyer.", author: "Jesse Pinkman" },
  { quote: "I've heard it said that a man's character is his fate.", author: "Nucky Thompson" },
  { quote: "Not great, Bob!", author: "Pete Campbell" },
  { quote: "Valar Morghulis. (All men must die)", author: "Various" },
  { quote: "Tell Cersei. I want her to know it was me.", author: "Olenna Tyrell" },
  { quote: "I drink and I know things.", author: "Tyrion Lannister" },
  { quote: "Today you, tomorrow me.", author: "A legendary Reddit comment" },
  { quote: "We judge others by their actions, but we judge ourselves by our intentions.", author: "Reddit" },
  { quote: "You don't have to set yourself on fire to keep other people warm.", author: "Reddit" },
  { quote: "The oldest picture of you is also the youngest picture of you.", author: "r/Showerthoughts" },
  { quote: "Nothing ruins a Friday more than realizing it's only Tuesday.", author: "r/Showerthoughts" },
  { quote: "Grief is just love with no place to go.", author: "Reddit" },
  { quote: "There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors.", author: "Classic developer joke" },
  { quote: "A user interface is like a joke. If you have to explain it, it’s not that good.", author: "r/ProgrammerHumor" },
  { quote: "Programming is like writing a book... except if you miss a single comma on page 126, the whole book makes no sense.", author: "r/ProgrammerHumor" },
  { quote: "Weeks of coding can save you hours of planning.", author: "Developer Sarcasm" },
  { quote: "'It works on my machine' should be a certified global tech excuse.", author: "r/ProgrammerHumor" },
  { quote: "Don't compare your Chapter 1 to someone else's Chapter 20.", author: "Instagram Motivation" },
  { quote: "Your comfort zone is a beautiful place, but nothing ever grows there.", author: "Instagram Motivation" },
  { quote: "A year from now, you will wish you had started today.", author: "Karen Lamb" },
  { quote: "Work in silence, let your success be your noise.", author: "Hustle Culture" },
  { quote: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln / Fitness Influencers" },
  { quote: "You cannot heal in the same environment that made you sick.", author: "Mental Health Advocates" },
  { quote: "Speak to yourself like someone you love.", author: "Self-Care Reminder" },
  { quote: "Healing is not linear.", author: "Therapy-gram" },
  { quote: "Rock bottom became the solid foundation on which I rebuilt my life.", author: "J.K. Rowling" },
  { quote: "Sometimes the most productive thing you can do is rest.", author: "Anti-Hustle Reminder" },
  { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Reddit" },
  { quote: "The days are long, but the years are short.", author: "Reddit" },
  { quote: "Comparison is the thief of joy.", author: "Reddit" },
  { quote: "No one is thinking about you as much as you are thinking about you.", author: "Reddit" },
  { quote: "You can be the ripest, juiciest peach in the world, and there's still going to be somebody who hates peaches.", author: "Reddit" },
  { quote: "Is it a bad day, or was it a bad five minutes that you let ruin the whole day?", author: "Reddit" },
  { quote: "If you smell poop everywhere you go, check your own shoe.", author: "Reddit" },
  { quote: "People don't fake being depressed. They fake being okay.", author: "Reddit" },
  { quote: "The axe forgets, but the tree remembers.", author: "Reddit" },
  { quote: "Embarrassment is the cost of entry for everything you want to do.", author: "Reddit" },
  { quote: "If it takes less than five minutes, do it now.", author: "Reddit" },
  { quote: "Motivation is fleeting; discipline is what gets it done.", author: "Reddit" },
  { quote: "A ship in harbor is safe, but that is not what ships are built for.", author: "Reddit" },
  { quote: "Everyone has a plan until they get punched in the face.", author: "Reddit" },
  { quote: "Play stupid games, win stupid prizes.", author: "Reddit" },
  { quote: "You are the average of the five people you spend the most time with.", author: "Reddit" },
  { quote: "Don't take criticism from someone you wouldn't take advice from.", author: "Reddit" },
  { quote: "The magic you are looking for is in the work you are avoiding.", author: "Reddit" },
  { quote: "It is possible to commit no mistakes and still lose. That is not a weakness; that is life.", author: "Reddit" },
  { quote: "Be the person you needed when you were younger.", author: "Reddit" },
  { quote: "I write code so that my computer can tell me I'm wrong at the speed of light.", author: "r/ProgrammerHumor" },
  { quote: "My code doesn't work, I have no idea why. My code works, I have no idea why.", author: "r/ProgrammerHumor" },
  { quote: "A programmer is a machine that turns caffeine into code.", author: "r/ProgrammerHumor" },
  { quote: "There is no cloud, it's just someone else's computer.", author: "r/ProgrammerHumor" },
  { quote: "Copying and pasting from Stack Overflow is not a crime, it's a lifestyle.", author: "r/ProgrammerHumor" },
  { quote: "Artificial Intelligence is no match for Natural Stupidity.", author: "r/ProgrammerHumor" },
  { quote: "The most permanent solution in software engineering is a temporary workaround.", author: "r/ProgrammerHumor" },
  { quote: "First, solve the problem. Then, write the code.", author: "r/ProgrammerHumor" },
  { quote: "If at first you don't succeed, call it version 1.0.", author: "r/ProgrammerHumor" },
  { quote: "Documentation is like sex: when it is good, it is very, very good; and when it is bad, it is better than nothing.", author: "r/ProgrammerHumor" },
  { quote: "I don't need a break, I need a breakpoint.", author: "r/ProgrammerHumor" },
  { quote: "Localhost is the only place I feel truly safe.", author: "r/ProgrammerHumor" },
  { quote: "Hackathons: where you build 80% of a startup in 24 hours and never look at the code again.", author: "r/ProgrammerHumor" },
  { quote: "It's not a bug, it's an undocumented feature.", author: "r/ProgrammerHumor" },
  { quote: "In theory, there is no difference between theory and practice. In practice, there is.", author: "r/ProgrammerHumor" },
  { quote: "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.", author: "r/ProgrammerHumor" },
  { quote: "Programming is 10% writing code and 90% understanding why it's not working.", author: "r/ProgrammerHumor" },
  { quote: "Algorithm (noun): Word used by programmers when they don't want to explain what they did.", author: "r/ProgrammerHumor" },
  { quote: "Git push --force: because sometimes you just have to assert dominance over your repository.", author: "r/ProgrammerHumor" },
  { quote: "Backend development is just moving JSON payloads from one server to another.", author: "r/ProgrammerHumor" },
  { quote: "Water is a beverage whose flavor is its temperature.", author: "r/Showerthoughts" },
  { quote: "When you say 'Forward' or 'Back', your lips actually move in those directions.", author: "r/Showerthoughts" },
  { quote: "The night before a day off is more satisfying than the actual day off.", author: "r/Showerthoughts" },
  { quote: "At some point, your parents picked you up, put you down, and never picked you up again.", author: "r/Showerthoughts" },
  { quote: "Your stomach thinks all potatoes are mashed.", author: "r/Showerthoughts" },
  { quote: "We are all just houseplants with complicated emotions.", author: "r/Showerthoughts" },
  { quote: "Clapping is just hitting yourself because you like something.", author: "r/Showerthoughts" },
  { quote: "You never truly realize how incredibly loud a plastic cake dome is until everyone else in the house is asleep.", author: "r/Showerthoughts" },
  { quote: "As a kid, my greatest fear was quicksand. Turns out, it's actually lower back pain.", author: "r/Showerthoughts" },
  { quote: "Teenage me would be very disappointed in current me, but current me could beat the crap out of teenage me.", author: "r/Showerthoughts" },
  { quote: "You are exactly where you need to be to get to where you want to go.", author: "Instagram" },
  { quote: "Growth is uncomfortable because you've never been here before.", author: "Instagram" },
  { quote: "Don't let the noise of others' opinions drown out your own inner voice.", author: "Instagram" },
  { quote: "Stop shrinking to fit places you've outgrown.", author: "Instagram" },
  { quote: "You didn't come this far to only come this far.", author: "Instagram" },
  { quote: "Your life is a reflection of your habits.", author: "Instagram" },
  { quote: "Create the highest, grandest vision possible for your life, because you become what you believe.", author: "Instagram" },
  { quote: "A flower does not think of competing with the flower next to it. It just blooms.", author: "Instagram" },
  { quote: "Starve your distractions, feed your focus.", author: "Instagram" },
  { quote: "Be addicted to the feeling of having your life put together.", author: "Instagram" },
  { quote: "Some chapters have to close without closure.", author: "Instagram" },
  { quote: "What comes easy won't last. What lasts won't come easy.", author: "Instagram" },
  { quote: "Trust the timing of your life.", author: "Instagram" },
  { quote: "You will never always be motivated, so you must learn to be disciplined.", author: "Instagram" },
  { quote: "If you are the smartest person in the room, you are in the wrong room.", author: "Instagram" },
  { quote: "Make your future self proud.", author: "Instagram" },
  { quote: "The comeback is always stronger than the setback.", author: "Instagram" },
  { quote: "Stop being afraid of what could go wrong, and focus on what could go right.", author: "Instagram" },
  { quote: "A comfort zone is a beautiful place, but nothing ever grows there.", author: "Instagram" },
  { quote: "Everything you want is on the other side of fear.", author: "Instagram" },
  { quote: "Be gentle with yourself, you're doing the best you can.", author: "Instagram" },
  { quote: "Note to self: You are enough.", author: "Instagram" },
  { quote: "It's okay to outgrow people who aren't growing.", author: "Instagram" },
  { quote: "Take a deep breath. You're going to figure it out, just like you always have.", author: "Instagram" },
  { quote: "Not everything is supposed to become something beautiful and long-lasting.", author: "Instagram" },
  { quote: "The way you speak to yourself matters.", author: "Instagram" },
  { quote: "You are allowed to take up space.", author: "Instagram" },
  { quote: "Your worth is not measured by your productivity.", author: "Instagram" },
  { quote: "Rest is not a reward, it is a necessity.", author: "Instagram" },
  { quote: "Fall in love with the process of becoming the very best version of yourself.", author: "Instagram" },
  { quote: "And into the forest I go, to lose my mind and find my soul.", author: "Instagram" },
  { quote: "Let it hurt, then let it go.", author: "Instagram" },
  { quote: "Protect your peace.", author: "Instagram" },
  { quote: "You are magic, don't ever apologize for the fire in you.", author: "Instagram" },
  { quote: "Whatever is good for your soul, do that.", author: "Instagram" },
  { quote: "In a world where you can be anything, be kind.", author: "Instagram" },
  { quote: "Sunsets are proof that endings can often be beautiful too.", author: "Instagram" },
  { quote: "Sometimes the bravest thing you can do is just keep going when you really feel like giving up.", author: "Instagram" },
  { quote: "You don't have to have it all figured out to move forward.", author: "Instagram" },
  { quote: "Breathe. It's just a bad day, not a bad life.", author: "Instagram" }
];

export function QuoteWidget() {
  const [quoteData, setQuoteData] = useState<QuoteData | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  const fetchQuote = useCallback(async (forceRefresh = false) => {
    setIsLoading(true);
    
    const todayStr = format(new Date(), 'yyyy-MM-dd');
    const cacheKey = 'daily_motivation_quote';
    const cachedDataStr = localStorage.getItem(cacheKey);

    if (!forceRefresh && cachedDataStr) {
      try {
        const cachedData = JSON.parse(cachedDataStr);
        if (cachedData.date === todayStr && cachedData.quote) {
          setQuoteData(cachedData.quote);
          setIsLoading(false);
          return;
        }
      } catch {
        // ignore parse error and fetch new
      }
    }

    try {
      // Simulate a brief loading state for smooth UI transition
      await new Promise(resolve => setTimeout(resolve, 300));
      
      // Pick a random quote from your preferred list
      const randomIndex = Math.floor(Math.random() * PREFERRED_QUOTES.length);
      const newQuote = PREFERRED_QUOTES[randomIndex];
      
      setQuoteData(newQuote);
      localStorage.setItem(cacheKey, JSON.stringify({ date: todayStr, quote: newQuote }));
    } catch (error) {
      console.error("Failed to fetch quote:", error);
      setQuoteData((prev) => prev || PREFERRED_QUOTES[0]);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchQuote();
  }, [fetchQuote]);

  return (
    <div className="bg-bg-card rounded-lg border border-border-subtle p-5 shadow-sm relative group overflow-hidden">
      <div className="flex items-center justify-between mb-3">
        <h2 className="text-body-md font-semibold text-text-main flex items-center gap-2">
          <Quote className="w-4 h-4 text-accent" /> Daily Motivation
        </h2>
        <button 
          onClick={() => fetchQuote(true)}
          disabled={isLoading}
          className="text-text-muted hover:text-accent transition-colors disabled:opacity-50"
          title="Get a new quote"
        >
          <RefreshCw className={`w-4 h-4 ${isLoading ? 'animate-spin text-accent' : ''}`} />
        </button>
      </div>
      
      <div className="min-h-[80px] flex flex-col justify-center">
        {isLoading && !quoteData ? (
          <div className="animate-pulse space-y-2">
            <div className="h-4 bg-border-subtle rounded w-full"></div>
            <div className="h-4 bg-border-subtle rounded w-5/6"></div>
            <div className="h-3 bg-border-subtle rounded w-1/3 mt-3"></div>
          </div>
        ) : (
          <div className="animate-fade-in relative z-10">
            <p className="text-body-sm text-text-main italic">"{quoteData?.quote}"</p>
            <p className="text-caption text-text-muted mt-2 font-medium text-right">— {quoteData?.author}</p>
          </div>
        )}
      </div>
      
      {/* Decorative background icon */}
      <Quote className="absolute -bottom-4 -right-2 w-24 h-24 text-border-subtle opacity-20 rotate-12 pointer-events-none group-hover:scale-110 transition-transform duration-500" />
    </div>
  );
}
